server:
  port: 8092

spring:
  application:
    name: cloud-ribbon

eureka:
  client:
    service-url:
      defaultZone: http://user:123456@localhost:8080/eureka/ #服务注册中信地址，含有BASIC认证的用户名和密码
  instance:
    prefer-ip-address: true #将IP注册到服务注册中心
