server:
  port: 8000

spring:
  application:
    name: cloud-zuul

eureka:
  client:
    service-url:
      defaultZone: http://user:123456@localhost:8080/eureka
    healthcheck:
      enabled: true  #健康检查（需要spring-boot-starter-actuator依赖）
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10  # 续约更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 10  # 续约到期时间（默认90秒）


#zuul代理配置  zuul.routes.服务名.path,服务名要与注册的一致
zuul:
  routes:
    api-provider:
      path: /api-provider/**
      service-id: cloud-provider  #应用名映射
    api-consumer:
      path: /api-consumer/**
      service-id: cloud-consumer  #应用名映射
  ignored-patterns: /**/admin/** #过滤掉匹配URL
  sensitive-headers:     #默认会过滤 "Cookie", "Set-Cookie", "Authorization" 会影响统一授权
#  strip-prefix: true    #默认时或true时 转发到服务的请求是/**，如果stripPrefix=false，转发的请求是直接/api-consumer/**
#  prefix: /api #会对所有的path增加一个/api前缀

