server:
  port: 8090

spring:
  application:
    name: cloud-provider

eureka:
  client:
    service-url:
      defaultZone: http://10.107.119.189:8080/eureka/
  instance:
    prefer-ip-address: true
